- .github/workflows/spec.yaml
The litmus_spec action uses the `--user-install` switch when installing
the `bundler` gem. This installs it to a directory that is not on the
PATH. Subsequent calls to `bundler` like `bundler -v` then fail and
cause the ci run to fail.
This change switches to a personal fork of the action that removes that
call.
When a fix for this bug is implemented in the upstream action repo this
change should be removed to point at the puppetlabs copy of the action.
> (MAINT) Fix gem --user-install bug

- .github/workflows/spec.yaml
The required fix has been merged into the puppetlabs namespaced repo.
Revert this change to go back to using the correct actions reference.
> (MAINT) Revert spec.yaml

- lib/common_events_library/util/common_events_http.rb
- spec/unit/util/common_events_http_spec.rb
The uri had a ? appended to it when it had a limit and offset of zero.
Added a new unit test to cover it.
> (PIE-451) Fix the make_params function for limit and offset being zero

- metadata.json
This module no longer has an manifests that would require this resource.
> (MAINT) Remove inifile module dependency

- lib/common_events_library/util/common_events_http.rb
- spec/unit/util/common_events_http_spec.rb
Previously we hard coded the ? character to the beginning of our
pagination params to signify the beginning of a uri query. This caused a
bug where a second ? could be added to the uri if another query was
passed as part of the uri. Now the uri query is completely deconstructed
and remade each time the make_params method is called.
> (PIE-465) Prevent double uri queries

- README.md
- lib/common_events_library/api/events.rb
- lib/common_events_library/api/orchestrator.rb
Modify the Events and Orchestrator classes to accept an auth token in
order to prevent a sensitive username and password from being stored in
a config file. In this scenario the user provides their own long lived
auth token rather than having the PEHTTP class generate one. Users are
still able to use a username and password if desired.
> (PIE-475) Allow Events and Orchestrator classes to accept auth token.

- .rubocop.yml
- files/collect_api_events.rb
- lib/events_collection/lockfile.rb
- spec/support/acceptance/install_pe.sh
- spec/unit/events_collection/lockfile_spec.rb
The coordinator script should wake up and be able to tell if the
previous run has completed. It should then write it's own lock file
to prevent a subsequent concurrent run.
The lock file should be fault tolerant and not leave an orphan lock
file if the script encounters an error.
It should also write enough information to the file so that the script
is not confused if the operating system reuses the PID in the case
that an orphan PID file is left behind for some reason.
> (PIE-654) Implement Lock File

- files/collect_api_events.rb
- files/util/index.rb
- spec/unit/util/common_events/index_spec.rb
Refactored the index class so that we don't need to create new instances
of the index class for every service_name endpoint. Initialize no longer
takes the service_name as param, but the sub functions do.
> PIE-764 Refactor Index class

- files/util/processor.rb
- rakelib/helpers.rake
- spec/spec_helper_local.rb
- spec/support/acceptance/proc1.sh
- spec/support/acceptance/proc2.rb
- spec/unit/util/common_events/processor_spec.rb
This change adds a class that knows how to search a specified directory
at only the first level looking for files, but not search recursively
through directories. Those directories may contain support library files
for the processors, not processors.
This class can then be created from a file path and it knows how to
invoke a processor and capture its output streams and exit code.
That data can then be accessed for logging purposes.
> (PIE-761) Implement Search for Processors

- files/api/events.rb
- files/util/index.rb
- spec/unit/util/common_events/index_spec.rb
Added function to events.rb to get the current total event count for the
specified service name.
Added quotations for two of the service names in index.rb to fix the
name. (pe_console -> pe-console, code_manager -> code-manager)
> PIE-758 Add get event count to events client

- files/collect_api_events.rb
- files/util/index.rb
- spec/unit/util/common_events/index_spec.rb
When the module is first started it should not send every event in the
api all at once. It should realize this is the first time it's running,
note the number of available events in the index file and then shut
down.
On the next run it should then only send the new events since that first
run.
> (PIE-525) HSBC Defect - First Run Protection

- files/api/activity.rb
- files/api/orchestrator.rb
- files/util/pe_http.rb
Removed call to the make_params method from orchestrator and activity
Pe_http can now build the URI internally
> (PIE-759) Moved make_params call to pe_http class

- files/collect_api_events.rb
- spec/spec_helper_local.rb
- spec/unit/util/common_events/logger_spec.rb
Removed the function that was mocking the settings file (not needed).
Put the logger setup lines in collect_api_events together for
consistency.
> MAINT Removed unneeded function for logger_spec

- rakelib/helpers.rake
The upload_processors rake task had an old path to install the test
processors onto the puppet server. It has been updated.
> (MAINT) Update location of test processors

- files/collect_api_events.rb
Fixed one of the log entries that had single quotes to double
quotes so interpolation works correctly now.
> MAINT - Fix Quoting Typo

- files/util/processor.rb
- spec/unit/util/common_events/processor_spec.rb
Directory searches were being done recursively. We don't want that to
happen because processors are allowed to write their own sub directories
and the files inside those directories should not be considered
processors themselves.
> (MAINT) Fix recursive directory search

- files/collect_api_events.rb
- lib/puppet/functions/common_events/base_path.rb
- manifests/init.pp
- spec/spec_helper_acceptance_local.rb
This change removes common_events feature files from the `puppet`
subdirectory under `/etc/puppetlabs`. Having files in the directory
implied that they were a part of core Puppet functionality.
> (MAINT) Move base config directory

- files/api/activity.rb
- files/api/orchestrator.rb
The functions get_events and get_jobs in activity.rb and
orchestrator.rb respectively, now concatenate the items array correctly
and the loop conditions for getting items from the API call now
check the correct array count.
The activity.rb specifically, now generates the correct final hash
with the key `commits`.
> MAINT Fix API Calling functions

- files/api/activity.rb
- files/api/orchestrator.rb
- files/util/index.rb
For consistency, made the resulting hash of `get_events` and `get_jobs`
from orchestrator.rb and activity.rb (respectively) to have the same
keys.
> MAINT Recreate Event Hashes

- .github/workflows/release.yml
The forge now uses an API key and a PDK docker container to deploy
to the forge from Github actions workflows. This change updates the
workflows to comply with the new process.
> (MAINT) Fix the forge deploy workflow

- CHANGELOG.md
- README.md
One customer has already noted, with some frustration, that they were
initially unable to get this module working, because they didn't know
that the `pe_password` parameter could not be assigned via the console.
This change ensures that future users will be warned and given a
workaround earlier in the implementation process.
> (MAINT) Document Sensitive param in README

- README.md
Updated README to have the correct variable name of api_page_size and
not api_window_size.
> MAINT - Fix name of old variable

- files/util/lockfile.rb
- spec/unit/util/pe_event_forwarding/lockfile_spec.rb
The collect_api_events.rb script will check if another instance of the
script is running and exit if so. The problem arises when the exit is
caught so we can create the appropriate log messages and an ensure block
deletes the lockfile. In scenarios where the cron calls start to stack
on each other this ensure clause can delete lockfiles created by other
running instances of collect_api_events.rb.
To solve this we introduce a check before deleting the lockfile to
ensure that the current pid matches the pid in the lockfile. There is a
force parameter to override this check which is used by the
validate_command in the case that the pid referenced in the lockfile no
longer exists.
> (PIE-1034) Ensure lockfile only deleted when appropriate

- README.md
Prior to this commit the docs did not specify which permissions the RBAC user needs to use pe_event_forwarding. This commit specifies that at least the job orchestrator permission is required
> (PIE-1060) Add token permissions to README

- manifests/init.pp
- spec/acceptance/class_spec.rb
Changes to `init.pp` to default cron owner to the `$owner` variable.
* Updated **L118** in `manifests/init.pp` from `root` -> `$owner`.
* Updated **L49** and **L49** `spec/acceptance/class_spec.rb` to include the `pe-puppet` user in the `crontab` command.
> (PIE-1162) Update cron user

- .devcontainer/devcontainer.json
- .github/workflows/integration_test.yml
- .github/workflows/spec.yml
- .pdkignore
- .rubocop.yml
- CHANGELOG.md
- Gemfile
- README.md
- REFERENCE.md
- Rakefile
- files/collect_api_events.rb
- files/util/index.rb
- files/util/logger.rb
- lib/puppet/functions/pe_event_forwarding/base_path.rb
- manifests/init.pp
- metadata.json
- plans/acceptance/pe_server.pp
- plans/acceptance/provision_machines.pp
- rakelib/helpers.rake
- spec/acceptance/index_spec.rb
- spec/spec_helper_local.rb
This commit contains changes made by `pdk`, `rubocop` and `lint`;  as well as manual changes to `metadata.json` to add Puppet 8.
Honeycomb steps have been removed from workflows `spec.yml` and `integration_test.yml`.
* **PDK Update**:
* `.devcontainer/devcontainer.json`
* `.rubocop.yml`
*  `.pdkignore`
* `Rakefile`
* `Gemfile`
* `.github/workflows/spec.yml`
* **Rubocop Changes**:
* `plans/acceptance/provision_machines.pp`
* `plans/acceptance/pe_server.pp`
* `lib/puppet/functions/pe_event_forwarding/base_path.rb`
* `files/util/logger.rb`
* `files/collect_api_events.rb`
* **Lint Changes**:
* `manifests/init.pp`
---
**Maint Changes**:
* `README.md`
* Add note about `v2` removing support for PE 2019.8.12.
* `metadata.json`
* Bumped module to `v2`. 
* Added Puppet 8 / Pulled Puppet 6 / Updated …
> (PIE-1300) Puppet 8 Compatibility

- CHANGELOG.md
- lib/puppet/functions/pe_event_forwarding/base_path.rb
- manifests/init.pp
This maintenance PR addresses a bug in the internal `base_path` function where a path in the cron command is created with a double slash (`//`) when a user provided path ends in a slash.
* Fix lint error in `init.pp` by utilizing Heredoc
* `lib/puppet/functions/pe_event_forwarding/base_path.rb`
* Remove any trailing `/` from user provided base path.
> (MAINT) Fix base_path function

- spec/functions/base_path_spec.rb
- spec/spec_helper_local.rb
Adding spec tests for the `base_path` function after removing the MockFunction from `splunk_hec`.
* Added `spec/functions/base_path_spec.rb`
* Updated `spec/spec_helper_local.rb` to set default dir paths.
> (PIE-1313) Add spec tests for base_path function

- CHANGELOG.md
- REFERENCE.md
- files/collect_api_events.rb
- files/collection_secrets.yaml.epp
- lib/puppet/functions/pe_event_forwarding/secure.rb
- manifests/init.pp
- manifests/v2_cleanup.pp
- spec/acceptance/class_spec.rb
- spec/classes/init_spec.rb
- templates/collection_settings.yaml.epp
This PR utilizes the  custom function `pe_event_forwarding::secure` to move credential data to a separate file.
* Added `manifests/v2_cleanup.pp`
* Added `files/collection_secrets.yaml.epp`
* Renamed `templates/events_collection.yaml.epp` -> `templates/collection_settings.yaml.epp`
* Updated `lib/puppet/functions/pe_event_forwarding/secure.rb`
* Function now accepts and returns a hash instead of string
* Updated `manifests/init.pp`
* Move credentials to `collection_secrets.yaml`
* Remove `events_collection.yaml` via `::v2_cleanup` subclass
* Updated `files/collect_api_events.rb`
* Utilize credentials from `collection_secrets.yaml`
* Generated updates for `REFERENCE.md`
* Updates spec tests
* `spec/acceptance/class_spec.rb`
* `spec/classes/init_spec.rb`
> (PIE-1328) secure sensitive data

- CHANGELOG.md
- README.md
- REFERENCE.md
- files/api/activity.rb
- files/collect_api_events.rb
- manifests/init.pp
- spec/spec_helper_acceptance_local.rb
- templates/collection_settings.yaml.epp
This commit adds the ability to filter which events to collect before collection occurs.
Updated `files/api/activity.rb`
* Removed `SERVICE_NAMES_WITHOUT_RBAC` as filtering is now done in `collect_api_events.rb`.
Updated `files/collect_api_events.rb`
* Check settings file to build list of service names to collect from the Activity API.
* Check settings file to determine if events should be collected from the Orchestrator API.
Updated `manifests/init.pp`
* Added new parameters `::skip_events` and `::skip_jobs`.
Updated `templates/collection_settings.yaml.epp`
* Add new parameters to the settings file template.
Updated `spec/spec_helper_acceptance_local.rb`
* Refactored tests against disabling rbac collection to utilize the `skip_events` parameter.
Documented changes in:
* `README.md`
* …
> (PIE-1460) Collection filtering feature

- CHANGELOG.md
- README.md
- REFERENCE.md
- files/api/activity.rb
- files/api/orchestrator.rb
- files/collect_api_events.rb
- files/util/http.rb
- files/util/pe_http.rb
- manifests/init.pp
- templates/collection_settings.yaml.epp
This commit adds an optional parameter `pe_event_forwarding::timeout` to allow users to configure the HTTP timeout used when collecting events.
* `manifests/init.pp`
* Added `timeout` parameter.
* `templates/collection_settings.yaml.epp`
* Added `timeout` parameter.
* `files/api/activity.rb`
* Updated class functions to accept timeout. 
* `files/api/orchestrator.rb`
* Updated class functions to accept timeout.
* `files/collect_api_events.rb`
* Added `timeout` variable with default of `60` seconds.
* `files/util/http.rb`
* Removed default timeout.
* Convert timeout to an integer.
* `files/util/pe_http.rb`
* Added debug log message to indicate what value was used for the timeout.
* Updated `README.md`
* Updated `REFERENCE.md`
* **Maintenance**:
* `manifests/init.pp` …
> (PIE-1462) Add timeout parameter
