CONTRIBUTING.md, README.md
Update the readme to include a few basic usage examples for the gem.
=> (PIE-420) Document Basic Usage

.fixtures.yml, .sync.yml, CONTRIBUTING.md, plans/acceptance/pe_server.pp, provision.yaml, rakelib/helpers.rake, spec/support/acceptance/helpers.rb
Modified helpers.rake acceptance tasks to move away from using scripts
to using bolt helper functions to execute plans that install PE.
Added to the CONTRIBUTING.md
=> PIE-725 Development Workflow

files/lib/util/logger.rb, spec/unit/util/logger_spec.rb
Created a logger.rb in lib/util that inherits from the Logger ruby
class.
Created a logger_spec testing the implemented logger.
=> PIE-657 Implement logging

.gitignore, .rubocop.yml, .sync.yml, files/collect_api_events.rb, files/lib/api/orchestrator.rb, files/lib/util/common_events_index.rb, spec/unit/util/common_events/index_tracker_spec.rb, spec/unit/util/common_events/logger_spec.rb
Added a class that knows how to track API item index numbers.
Create an instance of the class for each API index you want to track.
=> (PIE-655) Index Tracking Class

manifests/install.pp, spec/classes/install_spec.rb
Added file resources to create subdirs.
Added executable perms to collector script.
=> (PIE-760) Add new file resources to install class

files/util/index.rb, spec/spec_helper_local.rb, spec/unit/util/common_events/index_spec.rb
Remove redundant file reads
Add a count function
Improve save function
=> (MAINT) Improve Index Class

files/api/events.rb, files/api/orchestrator.rb, files/collect_api_events.rb, plans/acceptance/pe_server.pp
This change starts to put the pieces together in the events collection
script to gather the data and collect it into a useful form.
=> (PIE-776) Gather Events in Collection Script

manifests/init.pp, manifests/install.pp, spec/classes/install_spec.rb
Made changes to init.pp & install.pp to make the cron schedule configurable.
Made changes to allow for disabling the cron.
=> (PIE-696) Make cron schedule configurable

files/collect_api_events.rb, files/util/processor.rb, spec/spec_helper_local.rb, spec/support/acceptance/proc1.sh, spec/support/acceptance/proc2.rb, spec/unit/util/common_events/processor_spec.rb
This change implements writing temp files for each processor that gets
invoked.
=> (PIE-656) Temp Files for Processors

files/util/logger.rb, spec/unit/util/common_events/logger_spec.rb
Modified the logger class formatter and sub functions to accept the
exit code and append it to the output log message.
=> PIE-774 Modify Logger to accept exit code parameter

files/api/orchestrator.rb, files/collect_api_events.rb
Defaulted ordering to asc (reverse).
=> PIE-767 Ensure reverse order

files/api/activity.rb, files/api/orchestrator.rb, files/collect_api_events.rb, files/util/index.rb, files/util/processor.rb, scripts/tasks/activities.rb, scripts/tasks/events_orchestrator.rb, spec/spec_helper_local.rb, spec/unit/util/common_events/processor_spec.rb, tasks/activities.json, tasks/activities.rb
Clean up the code in the collection script and add a few helpers in
the classes to make the code easier to understand and more
maintainable.
=> (PIE-794) Maintenance Refactoring

files/collect_api_events.rb, manifests/install.pp, spec/classes/install_spec.rb
Updated cron and collector script to reflect new location.
Added file resources for required directories.
=> (PIE-763) Create lockfile in custom statedir.

README.md
Added puppet documentation link to README.md
=> PIE-491 Add Puppet Documentation Links to README

files/collect_api_events.rb, files/util/logger.rb, manifests/init.pp, spec/spec_helper_local.rb, spec/unit/util/common_events/logger_spec.rb, templates/events_collection.yaml.epp
Added a parameter that lets the user choose the severity level of logs
they want.
=> PIE-798 Implement Log Level Parameter

files/collect_api_events.rb, files/util/logger.rb, manifests/init.pp, spec/unit/util/common_events/logger_spec.rb, templates/events_collection.yaml.epp
Created a new parameter to implement log rotation, with a default of daily rotations.
=> (PIE-810) Implement log rotation parameter

.github/workflows/integration_test.yml, files/api/orchestrator.rb, plans/acceptance/pe_server.pp, plans/acceptance/provision_machines.pp, rakelib/helpers.rake, spec/acceptance/class_spec.rb, spec/acceptance/index_spec.rb, spec/spec_helper_acceptance.rb, spec/spec_helper_acceptance_local.rb, spec/support/acceptance/helpers.rb, tasks/orchestrator.json, tasks/orchestrator.rb
These changes add basic acceptance tests and the files required
to run them via github actions triggered by pull requests.
=> (PIE-800) Acceptance Test Framework

lib/puppet/functions/pe_event_forwarding/base_path.rb
Modify function to prevent returning the ending slash of the path.
=> (MAINT) Fix Base Path Function

manifests/init.pp, spec/acceptance/class_spec.rb, spec/classes/init_spec.rb
This directory was removed in a previous commit and needs to be added.
=> (MAINT) Add processors.d directory back

files/api/activity.rb, files/api/orchestrator.rb, files/collect_api_events.rb, manifests/init.pp, templates/events_collection.yaml.epp
Added and implemented a new parameter `api_window_size` that will set a
window size for how many events it will send per api call.
=> PIE-803 Max Number of Events to Request

REFERENCE.md, files/api/activity.rb, files/api/orchestrator.rb, files/collect_api_events.rb, manifests/init.pp, templates/events_collection.yaml.epp
Renamed api_window_size to api_page_size.
=> (MAINT) Rename api_window_size Variable

.github/workflows/spec.yml, .gitignore, .pdkignore, .sync.yml, appveyor.yml, metadata.json, plans/acceptance/provision_machines.pp, spec/spec_helper.rb
=> PIE-875 PDK Compliance

spec/support/acceptance/generate_rbac_event.rb
Added a nil check on count var.
Moved token var outside the method and added it in the signature.
=> (MAINT) Implement nil check for ARGV

files/api/activity.rb, files/api/orchestrator.rb, files/collect_api_events.rb, files/util/pe_http.rb
This change adds debug messages and changes some of the existing
messages to be info messages. This should allow better troubleshooting
of the bug referenced in the ticket and future bugs as well.
=> (PIE-958) Add Debug Messages

manifests/init.pp
Account for configured confdirs that are not the default
'etc/puppetlabs' in the manifest.
=> PIE-1032 Account for configured confdirs

tasks/activities.json, tasks/activities.rb
Fix typos in the activity task that were missed during the rename of this module.
* Updated `tasks/activities.rb` to point to the correct file location.
* Updated **files** in `tasks/activities.json` to point to the correct file location.
=> (MAINT) Update activity task code and metadata

CHANGELOG.md, metadata.json
Release Prep
* Updated version in `metadata.json`
=> (PIE-1246) release_prep

spec/support/acceptance/generate_classifier_event.rb
This PR includes changes to `generate_classifier_event.rb`.
* Ensure `generate_classifier_event.rb` runs with Puppet bundled Ruby.
=> (MAINT) Update support scripts for CI

lib/puppet/functions/pe_event_forwarding/secure.rb
This PR adds the custom function `pe_event_forwarding::secure`.
* Adds `lib/puppet/functions/pe_event_forwarding/secure.rb` to prepare for securing sensitive data utilized by this module.
=> (PIE-1340) Add custom function to secure data

.fixtures.yml, .github/workflows/integration_test.yml, files/collect_api_events.rb, plans/acceptance/pe_server.pp
This commit ensures compatibility with Ruby 3.
* `files/collect_api_events.rb`
* Added double splat to pass `**kwargs`.
* `.github/workflows/integration_test.yml`
* Added PE 2023.4 to test matrix.
[X] Unit Tests
[X] Acceptance Tests
[X] PR title is "(Ticket|Maint) Short Description"
[X] Commit title matches PR title
=> (MAINT) Ruby 3 compatibility for Puppet 8

CHANGELOG.md
=> (PIE-1317) release prep

CHANGELOG.md, README.md
This commit contains markdown format changes to `README.md`.
* Refactored `README.md`
* Updated `CHANGELOG.md` for z release.
=> (MAINT) Refactor README

metadata.json
Release prep for v2.0.1
* Bumped version in `metadata.json`.
=> (release_prep) v2.0.1

CHANGELOG.md, metadata.json, plans/acceptance/pe_server.pp, spec/support/acceptance/generate_rbac_event.rb
Release prep for **v2.1.0**
Updated
* `metadata.json`
* `CHANGELOG.md`
RuboCop Changes:
* `spec/support/acceptance/generate_rbac_event.rb`
* `plans/acceptance/pe_server.pp`
=> (PIE-1613) Release Prep
